services:
  rating-service:
    build: .
    container_name: rating-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - rating-postgres
    restart: always
    networks:
      - rating-network

  rating-postgres:
    image: postgres:15
    container_name: rating-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rating-network

volumes:
  pgdata:

networks:
  rating-network:
